config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :trips, only: [:index, :show]
  resources :orders, only: [:new, :create, :show]
  resources :items, only: [:show, :edit, :update]

  namespace :admin do
    resources :stations, only: [:new, :create, :edit, :update, :destroy], param: :slug
    resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :trips, only: [:new, :create, :edit, :update, :destroy]
    resources :items, only: [:new, :create, :edit, :update]
  end
  resources :items, only: [:show, :edit, :update]


  get '/admin/dashboard', to: 'admin/dashboards#index'
  get '/admin/bike-store', to: 'items#index'
  
  get '/bike-store', to: 'items#index'
  post '/cart_items', to: 'cart_items#create'
  post 'cart_items/:id/add', to: 'cart_items#add_item'
  post 'cart_items/:id/decrease', to: 'cart_items#decrease_item'
  delete '/cart_items', to: 'cart_items#destroy'
  get '/cart', to: 'cart_items#index'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/logout', to: "sessions#destroy"

  get '/dashboard', to: "dashboard#show"
  get '/stations-dashboard', to: "stations_dashboard#show"
  get '/trips-dashboard', to: "trips_dashboard#show"
  get '/conditions-dashboard', to: "conditions_dashboard#show"

  get '/:slug', to: 'stations#show', as: 'station'

end

app/models/station.rb
class Station < ApplicationRecord
  has_many :start_trips, class_name: "Trip", foreign_key: "start_station_id", dependent: :destroy
  has_many :end_trips, class_name: "Trip", foreign_key: "end_station_id", dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: [:slugged]
  validates_presence_of :name, :dock_count, :city, :installation_date

  def self.avg_bike_count
    Station.average(:dock_count)
  end

  def number_start_trips
    Trip.where(start_station_id: self.id).count
  end

  def number_end_trips
    Trip.where(end_station_id: self.id).count
  end

  def most_freq_destination
    #most frequent destination FROM this Station
    id = (Trip.where(start_station_id: self.id).group(:end_station_id).order("count_all DESC").count).keys.first
    Station.find(id)
  end

  def most_freq_origination
    #most frequent origination TO this Station
    id = (Trip.where(end_station_id: self.id).group(:start_station_id).order("count_all DESC").count).keys.first
    Station.find(id)
  end

  def date_most_start_trips
    (Trip.where(start_station_id: self.id).group(:start_date).order("count_all DESC").count).keys.first
  end

  def bike_id_most_start_trips
    (Trip.where(start_station_id: self.id).group(:bike_id).order("count_all DESC").count).keys.first
  end

end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController

  def show
    @station = Station.find(params[:id])
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.create(station_params)
    if @station.save
      flash[:notice] = "You created #{@station.name} Station"
      redirect_to station_path(@station)
    else
      render :new
    end
  end

  def edit
    @station = Station.friendly.find_by(params[:name])
  end

  def update
    @station = Station.friendly.find_by(params[:name])
    @station.update(station_params)
    if @station.save
      flash[:success] = "You updated #{@station.name} Station"
      redirect_to station_path(@station)
    else
      flash[:notice] = 'Station not updated'
      render :edit
    end
  end

  def destroy
    station = Station.friendly.find_by(params[:name])
    station.destroy

    flash[:success] = "Station deleted."
    redirect_to stations_path
  end

  private

  def station_params
    params.require(:station).permit(:name, :dock_count, :city, :installation_date)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.page(params[:page]).per(30)
  end

  def show
    @station = Station.friendly.find_by(params[:name])
  end
end

app/views/stations/index.html.erb
<h1>All Stations</h1>

<button type="button" class="btn btn-warning"><%= link_to "Go to Stations Dashboard", stations_dashboard_path%></button>

<% if current_admin? %>
<%= link_to "Add New Station", new_admin_station_path %>
<% end  %>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Station Name</th>
      <th scope="col">Dock Count</th>
      <th scope="col">City</th>
      <th scope="col">Installation Date</th>
      <% if current_admin?  %>
        <th></th>
        <th></th>
        <% end %>
    </tr>
  </thead>
  <% @stations.each do |station|  %>

  <tbody>
    <tr>
      <th scope="row"><%= link_to "#{station.name}", station_path(station.slug) %></th>
      <td><%= station.dock_count %></td>
      <td><%= station.city %></td>
      <td><%= station.installation_date.strftime("%m-%d-%Y") %></td>
      <% if current_admin? %>
      <td><%= link_to "Edit", edit_admin_station_path(station) %></td>
      <td><%= link_to "Delete", admin_station_path(station), method: "delete" %></td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

<%= paginate @stations %>

app/views/stations/show.html.erb
<h1>Station: <%= @station.name %></h1>

<ul>
  <li>Dock Count: <%= @station.dock_count %></li>
  <li>City: <%= @station.city %></li>
  <li>Installation Date: <%= @station.installation_date %></li>

  <% if @station.start_trips.first && @station.end_trips.first %>
    <li>Total Number of Trips Started at this Station: <%= @station.number_start_trips %></li>
    <li>Total Number of Trips Ended at this Station: <%= @station.number_end_trips %></li>
    <li>Most Frequent Destination from this Station: <%= @station.most_freq_destination.name %></li>
    <li>Most Frequent Origination to this Station: <%= @station.most_freq_origination.name %></li>
    <li>Date of Most Trips Originated from this Station: <%= @station.date_most_start_trips.strftime("%F") %></li>
    <li>Bike ID with Most Trips Originated from this Station: <%= @station.bike_id_most_start_trips %></li>
  <% end %>
  <% if current_admin? %>
  <li><%= link_to "Edit", edit_admin_station_path(@station) %></li>
  <li><%= link_to "Delete", admin_station_path(@station), method: "delete" %></li>
  <% end  %>
</ul>

<h5><%= link_to "<< Back to All Stations", stations_path %></h5>