config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :trips, only: [:index, :show]
  resources :orders, only: [:new, :create, :show]
  resources :items, only: [:show, :edit, :update]

  namespace :admin do
    resources :stations, only: [:new, :create, :edit, :update, :destroy], param: :slug
    resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :trips, only: [:new, :create, :edit, :update, :destroy]
    resources :items, only: [:new, :create, :edit, :update]
  end
  resources :items, only: [:show, :edit, :update]


  get '/admin/dashboard', to: 'admin/dashboards#index'
  get '/admin/bike-store', to: 'items#index'
  
  get '/bike-store', to: 'items#index'
  post '/cart_items', to: 'cart_items#create'
  post 'cart_items/:id/add', to: 'cart_items#add_item'
  post 'cart_items/:id/decrease', to: 'cart_items#decrease_item'
  delete '/cart_items', to: 'cart_items#destroy'
  get '/cart', to: 'cart_items#index'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/logout', to: "sessions#destroy"

  get '/dashboard', to: "dashboard#show"
  get '/stations-dashboard', to: "stations_dashboard#show"
  get '/trips-dashboard', to: "trips_dashboard#show"
  get '/conditions-dashboard', to: "conditions_dashboard#show"

  get '/:slug', to: 'stations#show', as: 'station'

end

app/models/cart_item.rb
class CartItem < SimpleDelegator
  attr_reader :quantity
  def initialize(item, quantity=0)
    super(item)
    @quantity = quantity
  end

  def subtotal(item)
    item.price * @quantity
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    item = Item.find(params[:item_id])
    cart.add_item(item)
    session[:cart] = cart.data
    flash[:success] = "#{item.title} added to cart!"
    redirect_to bike_store_path
  end

  def add_item
    item = Item.find(params[:id])
    cart.add_item(item)
    session[:cart] = cart.data
    redirect_to cart_path
  end

  def decrease_item
    item = Item.find(params[:id])
    cart.decrease_item(item)
    session[:cart] = cart.data
    redirect_to cart_path
  end

  def index
    @cart_items = cart.items
  end

  def destroy
    item = Item.find(params[:item_id])
    cart.remove_item(item.id)
    redirect_to cart_path
    flash[:notice] = "#{item.title} removed from cart. Add it back in here:#{view_context.link_to(" #{item.title}", item_path(item))}"

  end
    # flash[:success] = "#{cart_item.title} has been deleted"
end

app/views/cart_items/index.html.erb
<table>
  <th>Name</th>
  <th>Quantity</th>
  <th>Add</th>
  <th>Decrease</th>
  <th>Price</th>
  <th>Image</th>
  <th>Subtotal</th>
  <% @cart_items.each do |cart_item| %>
  <tr>
    <td class="title-#{cart_item.id}"><%= cart_item.title %></td>
    <td class="quantity-#{cart_item.id}"><%= cart_item.quantity %></td>
    <td class="increase_button-#{cart_item.id}"><%= button_to "+", "/cart_items/#{cart_item.id}/add" %></td>
    <td class="increase_button-#{cart_item.id}">
      <% if cart_item.quantity == 1 %><%= button_to "-", "/cart_items/#{cart_item.id}/decrease", disabled: true %>
      <% else %><%= button_to "-", "/cart_items/#{cart_item.id}/decrease" %>
      <% end %>
    </td>
    <td class="price-#{cart_item.id}"><%= number_to_currency(cart_item.price) %></td>
    <td class="image-#{cart_item.id}"><%= image_tag("#{cart_item.image_url}" , size: "30")%></td>
    <td class="subtotal-#{cart_item.id}"><%= number_to_currency(cart_item.subtotal(cart_item)) %></td>
    <td class="remove_item-#{cart_item.id}"><%= button_to 'Remove', cart_items_path(item_id: cart_item.id), method: :delete%></td>
       </tr>
  <% end %>
</table>

<h2>Cart Total</h2>
<p><%= number_to_currency(@cart.total) %></p>
<% if current_user %>
<p><%= button_to "Checkout", orders_path %></p>
<% else %>
<p class='sign-in-checkout'><%= button_to "Sign In To Checkout", login_path %></p>
<p><%= button_to "Sign Up To Checkout", new_user_path, method: :get %></p>
<% end %>