config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :trips, only: [:index, :show]
  resources :orders, only: [:new, :create, :show]
  resources :items, only: [:show, :edit, :update]

  namespace :admin do
    resources :stations, only: [:new, :create, :edit, :update, :destroy], param: :slug
    resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :trips, only: [:new, :create, :edit, :update, :destroy]
    resources :items, only: [:new, :create, :edit, :update]
  end
  resources :items, only: [:show, :edit, :update]


  get '/admin/dashboard', to: 'admin/dashboards#index'
  get '/admin/bike-store', to: 'items#index'
  
  get '/bike-store', to: 'items#index'
  post '/cart_items', to: 'cart_items#create'
  post 'cart_items/:id/add', to: 'cart_items#add_item'
  post 'cart_items/:id/decrease', to: 'cart_items#decrease_item'
  delete '/cart_items', to: 'cart_items#destroy'
  get '/cart', to: 'cart_items#index'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/logout', to: "sessions#destroy"

  get '/dashboard', to: "dashboard#show"
  get '/stations-dashboard', to: "stations_dashboard#show"
  get '/trips-dashboard', to: "trips_dashboard#show"
  get '/conditions-dashboard', to: "conditions_dashboard#show"

  get '/:slug', to: 'stations#show', as: 'station'

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items
  validates :title, uniqueness: true, presence: true
  validates_presence_of :description
  validates_presence_of :price
  validates_presence_of :image_url

  enum status: ["active", "retired"]

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      flash[:notice] = "#{@item.title} added to all Bike Accessories"
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:success] = "Item #{@item.title} edited"
      redirect_to admin_bike_store_path
    else
      flash[:notice] = "Item not updated"
      render :edit
    end
  end


  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :image_url, :status)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:success] = "Item #{@item.title} edited"
      redirect_to admin_bike_store_path
    else
      flash[:notice] = "Item not updated"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :image_url, :status)
  end

end

app/views/items/index.html.erb
<h1>Bike Accessories</h1>

<% if current_admin? %>
<%= link_to "Add New Bike Accessory", new_admin_item_path %>
<% end  %>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Item</th>
      <th scope="col">Image</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col"></th>
      <% if current_admin?  %>
        <th></th>
        <th></th>
        <% end %>
    </tr>
  </thead>
  <% @items.each do |item| %>

  <tbody>
    <tr>
      <th scope="row"><%= link_to "#{item.title}", item_path(item) %></th>
      <td>
        <img><%= image_tag("#{item.image_url}" , size: "50")%></img>
      </td>
      <td><%= item.description %></td>
      <td><%= number_to_currency(item.price) %></td>
      <td>
      <a href="#"><% if item.retired? %>
        <li><%= button_to "Unavailable", cart_items_path(item_id: item.id), disabled: true%></li>
      <% else %>
        <li id="item-<%= item.id %>"><%= button_to "Add to Cart", cart_items_path(item_id: item.id)%></li>
      <% end %>
      </a>
    </td>
      <% if current_admin? %>
        <td><%= link_to "Edit", edit_admin_item_path(item) %></td>
        <td>
          <div class='form'>
          <%= form_for [:admin, item] do |f| %>
          <div>
            <%= f.label :status %>
            <%= f.select :status, options_for_select([["active"],["retired"]]) %>
          </div>
          <td>
            <div>
              <%= f.submit "Submit"%>
            </div>
          </td>
            <% end %>
          </div>
        </td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/items/show.html.erb
<h1>Item: <%= @item.title %></h1>

<ul>
  <li><img src="<%= @item.image_url %>" class="img-fluid" alt="Responsive image"></li>
  <li> Price: <%= number_to_currency(@item.price) %> </li>
  <li> Description: <%= @item.description %> </li>
  <% if @item.retired? %>
    <li><%= button_to "Unavailable", cart_items_path(item_id: @item.id), disabled: true%></li>
  <% else %>
    <li><%= button_to "Add to Cart", cart_items_path(item_id: @item.id)%></li>
  <% end %>
  <% if current_admin? %>
    <%= link_to "<< Back to all Accessories", admin_bike_store_path %>
  <% else %>
    <%= link_to "<< Back to all Accessories", bike_store_path %>
  <% end %>
</ul>