config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :stations, only: [:index]
  resources :conditions, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :trips, only: [:index, :show]
  resources :orders, only: [:new, :create, :show]
  resources :items, only: [:show, :edit, :update]

  namespace :admin do
    resources :stations, only: [:new, :create, :edit, :update, :destroy], param: :slug
    resources :conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :trips, only: [:new, :create, :edit, :update, :destroy]
    resources :items, only: [:new, :create, :edit, :update]
  end
  resources :items, only: [:show, :edit, :update]


  get '/admin/dashboard', to: 'admin/dashboards#index'
  get '/admin/bike-store', to: 'items#index'
  
  get '/bike-store', to: 'items#index'
  post '/cart_items', to: 'cart_items#create'
  post 'cart_items/:id/add', to: 'cart_items#add_item'
  post 'cart_items/:id/decrease', to: 'cart_items#decrease_item'
  delete '/cart_items', to: 'cart_items#destroy'
  get '/cart', to: 'cart_items#index'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  get '/logout', to: "sessions#destroy"

  get '/dashboard', to: "dashboard#show"
  get '/stations-dashboard', to: "stations_dashboard#show"
  get '/trips-dashboard', to: "trips_dashboard#show"
  get '/conditions-dashboard', to: "conditions_dashboard#show"

  get '/:slug', to: 'stations#show', as: 'station'

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def index
    @orders = Order.all
    @sorted_orders = Order.by_status
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @user = current_user
    @user_orders = Order.where(user_id: @user.id)
  end

end

app/views/admin/dashboards/index.html.erb
<h1>Admin Dashboard</h1>

<%= link_to "See All Accessories - Go to Bike Shop", admin_bike_store_path %>

<h4>Total Orders Completed: <%= @sorted_orders["completed"] %></h4>
<h4>Total Orders Ordered: <%= @sorted_orders["ordered"] %></h4>
<h4>Total Orders Paid: <%= @sorted_orders["paid"] %></h4>
<h4>Total Orders Cancelled: <%= @sorted_orders["cancelled"] %></h4>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Order</th>
      <th scope="col">Status</th>
      <th scope="col">Date</th>
    </tr>
  </thead>

<% @orders.each do |order| %>

<tbody>
  <tr>
    <th scope="row"><%= link_to "Order-#{order.id}", order_path(order) %></th>
    <td id="order-<%= order.id %>"><%= order.status %></td>
    <td><%= order.created_at.strftime("%m-%d-%Y") %></td>
  </tr>
</tbody>
<% end %>
</table>